# 开发环境配置
server:
  # 服务器的 HTTP 端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /admin
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  # 模板引擎
  mvc:
    view:
      prefix: /templates
    # 抛出 404 等异常
    throw-exception-if-no-handler-found: true
  # 关闭工程中的资源文件建立映射
  resources:
    add-mappings: false