# 开发环境配置
server:
  # 服务器的 HTTP 端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /admin
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  # 模板引擎
  mvc:
    view:
      prefix: /templates
    # 抛出 404 等异常
    throw-exception-if-no-handler-found: true
  # 关闭工程中的资源文件建立映射
  resources:
    add-mappings: false
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sugar?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sa000
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化提供的连接数
      initial-size: 5
      # 最大的连接数
      max-total: 10
      # 等待连接获取的最大超时时间
      max-wait-millis: 10000
  # redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 客户端配置
    lettuce:
      # 连接池配置
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0